//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiNa.InventorAddInDebugger.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MiNa.InventorAddInDebugger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon AboutCmd_Dark {
            get {
                object obj = ResourceManager.GetObject("AboutCmd_Dark", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show about information.
        /// </summary>
        internal static string AboutCmd_Description {
            get {
                return ResourceManager.GetString("AboutCmd_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutCmd_DisplayName {
            get {
                return ResourceManager.GetString("AboutCmd_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon AboutCmd_Ligh {
            get {
                object obj = ResourceManager.GetObject("AboutCmd_Ligh", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show about information.
        /// </summary>
        internal static string AboutCmd_ToolTip {
            get {
                return ResourceManager.GetString("AboutCmd_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activates the AddIn.
        /// </summary>
        internal static string ActivateAddInCmd_Description {
            get {
                return ResourceManager.GetString("ActivateAddInCmd_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string ActivateAddInCmd_DisplayName {
            get {
                return ResourceManager.GetString("ActivateAddInCmd_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activates the AddIn.
        /// </summary>
        internal static string ActivateAddInCmd_ToolTip {
            get {
                return ResourceManager.GetString("ActivateAddInCmd_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ActivateCmd_Dark {
            get {
                object obj = ResourceManager.GetObject("ActivateCmd_Dark", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ActivateCmd_Light {
            get {
                object obj = ResourceManager.GetObject("ActivateCmd_Light", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddIn loader.
        /// </summary>
        internal static string AddIn_DisplayName {
            get {
                return ResourceManager.GetString("AddIn_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon AttachDebuggerCmd_Dark {
            get {
                object obj = ResourceManager.GetObject("AttachDebuggerCmd_Dark", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach debugger to the current Inventor instance.
        /// </summary>
        internal static string AttachDebuggerCmd_Description {
            get {
                return ResourceManager.GetString("AttachDebuggerCmd_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach debugger.
        /// </summary>
        internal static string AttachDebuggerCmd_DisplayName {
            get {
                return ResourceManager.GetString("AttachDebuggerCmd_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon AttachDebuggerCmd_Light {
            get {
                object obj = ResourceManager.GetObject("AttachDebuggerCmd_Light", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach debugger to the current Inventor instance.
        /// </summary>
        internal static string AttachDebuggerCmd_ToolTip {
            get {
                return ResourceManager.GetString("AttachDebuggerCmd_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivates the AddIn.
        /// </summary>
        internal static string DeactivateAddInCmd_Description {
            get {
                return ResourceManager.GetString("DeactivateAddInCmd_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        internal static string DeactivateAddInCmd_DisplayName {
            get {
                return ResourceManager.GetString("DeactivateAddInCmd_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivates the AddIn.
        /// </summary>
        internal static string DeactivateAddInCmd_ToolTip {
            get {
                return ResourceManager.GetString("DeactivateAddInCmd_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon DeactivateCmd_Dark {
            get {
                object obj = ResourceManager.GetObject("DeactivateCmd_Dark", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon DeactivateCmd_Light {
            get {
                object obj = ResourceManager.GetObject("DeactivateCmd_Light", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation of Add-In failed!
        ///%s.
        /// </summary>
        internal static string Msg_ActivationOfAddInFailed {
            get {
                return ResourceManager.GetString("Msg_ActivationOfAddInFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO
        ///AddIn is not activated..
        /// </summary>
        internal static string Msg_AddInNotActivated {
            get {
                return ResourceManager.GetString("Msg_AddInNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING
        ///AddIn not found.
        /// </summary>
        internal static string Msg_AddInNotFound {
            get {
                return ResourceManager.GetString("Msg_AddInNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO
        ///Already activated.
        /// </summary>
        internal static string Msg_AlreadyActivated {
            get {
                return ResourceManager.GetString("Msg_AlreadyActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command %s failed
        ///%s.
        /// </summary>
        internal static string Msg_CommandFailedGeneral {
            get {
                return ResourceManager.GetString("Msg_CommandFailedGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deactivation of Add-In failed!
        ///%s.
        /// </summary>
        internal static string Msg_DeactivationOfAddInFailed {
            get {
                return ResourceManager.GetString("Msg_DeactivationOfAddInFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload of Add-In failed!
        ///%s.
        /// </summary>
        internal static string Msg_ReloadOfAddInfailed {
            get {
                return ResourceManager.GetString("Msg_ReloadOfAddInfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully activated.
        /// </summary>
        internal static string Msg_SuccessfullyActivated {
            get {
                return ResourceManager.GetString("Msg_SuccessfullyActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deactivated.
        /// </summary>
        internal static string Msg_SuccessfullyDeactivated {
            get {
                return ResourceManager.GetString("Msg_SuccessfullyDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully reloaded.
        /// </summary>
        internal static string Msg_SuccessfullyReloaded {
            get {
                return ResourceManager.GetString("Msg_SuccessfullyReloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon OpenBuildFolderCmd_Dark {
            get {
                object obj = ResourceManager.GetObject("OpenBuildFolderCmd_Dark", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens folder with loaded build.
        /// </summary>
        internal static string OpenBuildFolderCmd_Description {
            get {
                return ResourceManager.GetString("OpenBuildFolderCmd_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open build folder.
        /// </summary>
        internal static string OpenBuildFolderCmd_DisplayName {
            get {
                return ResourceManager.GetString("OpenBuildFolderCmd_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon OpenBuildFolderCmd_Light {
            get {
                object obj = ResourceManager.GetObject("OpenBuildFolderCmd_Light", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens folder with loaded build.
        /// </summary>
        internal static string OpenBuildFolderCmd_ToolTip {
            get {
                return ResourceManager.GetString("OpenBuildFolderCmd_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloads the AddIn.
        /// </summary>
        internal static string ReloadAddInCmd_Description {
            get {
                return ResourceManager.GetString("ReloadAddInCmd_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string ReloadAddInCmd_DisplayName {
            get {
                return ResourceManager.GetString("ReloadAddInCmd_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloads the AddIn.
        /// </summary>
        internal static string ReloadAddInCmd_ToolTip {
            get {
                return ResourceManager.GetString("ReloadAddInCmd_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon RestartCmd_Dark {
            get {
                object obj = ResourceManager.GetObject("RestartCmd_Dark", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon RestartCmd_Light {
            get {
                object obj = ResourceManager.GetObject("RestartCmd_Light", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon SettingsCmd_Dark {
            get {
                object obj = ResourceManager.GetObject("SettingsCmd_Dark", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit settings of the AddIn.
        /// </summary>
        internal static string SettingsCmd_Description {
            get {
                return ResourceManager.GetString("SettingsCmd_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SettingsCmd_DisplayName {
            get {
                return ResourceManager.GetString("SettingsCmd_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon SettingsCmd_Light {
            get {
                object obj = ResourceManager.GetObject("SettingsCmd_Light", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit settings of the AddIn.
        /// </summary>
        internal static string SettingsCmd_ToolTip {
            get {
                return ResourceManager.GetString("SettingsCmd_ToolTip", resourceCulture);
            }
        }
    }
}
